### ISSUE TITLE
Cannot Install Service from Arbitrary Folder with Full Paths

### ISSUE THREAD

**Issue by sonuame** [kohsuke/winsw#1015]
**Summary**
Unable to install service in latest version

## Steps to reproduce
WinSW is located in Folder A
Service Xml is located in Folder B

Installing the service like this 
"C:\Apps\sites\live-cams\winsw.exe" install "C:\Apps\sites\live-cams\cam-services\31238005\31238005.xml"

Getting Error 

```
2023-02-18 23:30:12,783 FATAL - Unhandled exception
System.IO.FileNotFoundException: Unable to locate winsw.[xml|yml] file within executable directory
   at WinSW.Program.LoadConfigAndInitLoggers(Boolean inConsoleMode)
   at WinSW.Program.Run(String[] argsArray, IServiceConfig config)
   at WinSW.Program.Main(String[] args)
```
Why its expecting for winsw.xml ??

```xml
<service>
  <id>center_cam_31238005</id>
  <name>Cam-31238005</name>
  <description>Training Center Camera - Test - 31238005</description>
  <executable>C:\Apps\sites\live-cams\FFMpegWrapper.exe</executable>
  <arguments>SOME ARGUMENTS</arguments>
  <logpath>C:\Apps\sites\live-cams\stream-logs</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>1024</sizeThreshold>
    <keepFiles>10</keepFiles>
  </log>
  <workingdirectory>C:\Apps\sites\live-cams\output\31238005</workingdirectory>
  <startmode>Manual</startmode>
</service>
```

## Environment

* WinSW version: Latest Build
* WinSW package type: x64, dotnet 7.0
* Windows version: 11
* Wrapped executable and version: Internal EXE

## Possible Solution
Previous Version works great
Its a possible bug. Earlier version can install service from any folder with full path specified

**Comment by RibomBalt** [comment]
Related to #970 

It seems the "latest" master branch (v2.12.0) didn't support config files with different names from executables', while the actually more recent v3 alpha branches support (this feature seems to be added this from 3.0.0-alpha.7). They have updated the `readme.md` on the home page to v3, but the release listed on the right is still at v2, since v3 is still in alpha phase (pre-release). This may create confusions somehow.

For anyone curious about the responsible codes:

- v2.12.0: 

https://github.com/winsw/winsw/blob/eef5bade59fca0254e387ac73ed7625ba6aa7147/src/WinSW/Program.cs#L697-L704

- v3.0.0-alpha.11 (most recent alpha):

https://github.com/winsw/winsw/blob/a6ba41681d84d84d95eb7a377c369d709e32225b/src/WinSW/Program.cs#L1118-L1132

**Comment by aixj1984** [comment]
use [WinSW v3.0.0-alpha.11](https://github.com/winsw/winsw/releases/tag/v3.0.0-alpha.11) test, is ok
