### ISSUE TITLE
Exception Info: System.ObjectDisposedException: Cannot access a closed file.

### ISSUE THREAD

**Issue by KKatationer** [kohsuke/winsw#1016]
## Steps to reproduce

Service died in 3:00 a.m.
Windws Event Log:

Application: WinSW.exe
CoreCLR Version: 6.0.1322.58009
.NET Version: 6.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Write(Byte[] , Int32 , Int32 )
   at WinSW.StreamCopyOperation.CopyLine()
   at WinSW.RollingSizeTimeLogAppender.CopyStreamWithRotation(StreamReader reader, String extension)
   at WinSW.RollingSizeTimeLogAppender.<>c__DisplayClass22_0.<LogOutput>b__0()
   at System.Threading.Thread.StartCallback()

```xml
<log mode="roll-by-size-time">
  <sizeThreshold>10240</sizeThreshold>
  <pattern>yyyyMMdd</pattern>
  <autoRollAtTime>00:00:00</autoRollAtTime>
</log>
```

## Environment

* WinSW version: 2.12.0
* WinSW package type: .NET 6.0.13
* Windows version: Windows Server 2022
* Wrapped executable and version:  internal project

## Possible Solution

Change xml file to this:
```xml
<log mode="append"></log>
```

**Comment by zhengye1** [comment]
If I remember correctly ```append``` will just put all the log into one file right?

**Comment by JorisKimpe** [comment]
Is there a solution/workaround already for this issue?  

I have the same issue for a Spring Boot application wrapped as a windows service using winsw.
The windows service stops (but Spring Boot process keeps running)... 

In the Windows event viewer I have the same exception:
> CoreCLR Version: 6.0.1322.58009 
.NET Version: 6.0.13 
Description: The process was terminated due to an unhandled exception. 
Exception Info: System.ObjectDisposedException: Cannot access a closed file. 
      at System.IO.FileStream.Write(Byte[] , Int32 , Int32 ) 
      at WinSW.StreamCopyOperation.CopyLine() 
      at WinSW.RollingSizeTimeLogAppender.CopyStreamWithRotation(StreamReader reader, String extension) 
      at WinSW.RollingSizeTimeLogAppender.<>c__DisplayClass22_0.<LogOutput>b__0() 
      at System.Threading.Thread.StartCallback()

**Comment by KKatationer** [comment]
> Is there a solution/workaround already for this issue?
> 
> I have the same issue for a Spring Boot application wrapped as a windows service using winsw. The windows service stops (but Spring Boot process keeps running)...
> 
> In the Windows event viewer I have the same exception:
> 
> > CoreCLR Version: 6.0.1322.58009
> > .NET Version: 6.0.13
> > Description: The process was terminated due to an unhandled exception.
> > Exception Info: System.ObjectDisposedException: Cannot access a closed file.
> > at System.IO.FileStream.Write(Byte[] , Int32 , Int32 )
> > at WinSW.StreamCopyOperation.CopyLine()
> > at WinSW.RollingSizeTimeLogAppender.CopyStreamWithRotation(StreamReader reader, String extension)
> > at WinSW.RollingSizeTimeLogAppender.<>c__DisplayClass22_0.b__0()
> > at System.Threading.Thread.StartCallback()

Probably not, I ended up modifying the way the program records logs and it's very stable at the moment.

**Comment by MuirisOG** [comment]
I've changed the setting to 
```xml
	<log mode="roll-by-time">
	  <pattern>yyyyMMdd</pattern>
	</log>
```
... but I still get the error.

**Comment by JorisKimpe** [comment]
I am using "roll-by-size" now without issues:

```
	<log mode="roll-by-size">
		<sizeThreshold>10240</sizeThreshold>
		<keepFiles>5</keepFiles>
	</log>
```

**Comment by cpesch** [comment]
Did anyone look into this and found a fix in the code? Or in the v3 branch?

**Comment by KKatationer** [comment]
> Did anyone look into this and found a fix in the code? Or in the v3 branch?

This project might be deprecated. :(
It's already .NET 9 now, but it's still using .NET 6.

**Comment by cpesch** [comment]
You wrote:

> Probably not, I ended up modifying the way the program records logs and it's very stable at the moment.

what exactly did you change?
