### ISSUE TITLE
Time and size based log rollover throws an exception and stops logging

### ISSUE THREAD

**Issue by thomasdewaelheyns** [kohsuke/winsw#1034]
**Summary**
The Size and Time based log rollover strategy throws an exception in the windows event log when a time based rollover occurs while the main application is logging to the console.

The following error message is logged in the windows event log:
```
Unhandled exception in task. System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at WinSW.StreamCopyOperation.<CopyLineAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WinSW.RollingSizeTimeLogAppender.<CopyStreamWithRotationAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WinSW.AbstractFileLogAppender.<SafeLogOutput>d__13.MoveNext()
```

This results in a deadlock in the application since it will never be able to write to the output steam.

## Steps to reproduce

Have winsw use the "roll-by-size-time" log mode. An example of a configuration can be found below. At the same time have an application that is being started have frequent writes at the time of the rollover.

```xml
  <log mode="roll-by-size-time">
     <sizeThreshold>102400</sizeThreshold>
     <pattern>yyyyMMdd</pattern>
     <autoRollAtTime>00:00:00</autoRollAtTime>
     <keepFiles>30</keepFiles>
  </log>
```

## Environment

* WinSW version: WinSW v3.0.0-alpha.10
* WinSW package type: WinSW-x64.exe
* Windows version: Windows Server 2019 Datacenter
* Wrapped executable and version: java spring boot application using logback writing to the console

**Comment by DreamapleHT** [comment]
How was it resolved?
Has this bug been fixed yet?
