### ISSUE TITLE
WinSW.Extensions.ExtensionException: killOnStartup: Cannot load the class by name: WinSW.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension

### ISSUE THREAD

**Issue by muskhd** [kohsuke/winsw#1043]
**Summary**. 
Dear, I need help with the reported error.

Thank you very much.

## Steps to reproduce
When this extension is enabled, the service does not start.

2023-06-28 10:38:33,344 ERROR - Failed to start service.
WinSW.Extensions.ExtensionException: killOnStartup: Cannot load the class by name: WinSW.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension
 ---> WinSW.Extensions.ExtensionException: killOnStartup: Class WinSW.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension does not exist
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   --- End of inner exception stack trace ---
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensionFromXml(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtension(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensions()
   at WinSW.WrapperService.DoStart()
   at WinSW.WrapperService.OnStart(String[] args)

```xml
  <extensions>
    <!-- This is a sample configuration for the RunawayProcessKiller extension. -->
    <extension enabled="true" 
               className="winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension"
               id="killOnStartup">
      <pidfile>%BASE%\jenkins_agent.pid</pidfile>
      <stopTimeout>5000</stopTimeout>
      <stopParentFirst>true</stopParentFirst>
    </extension>
  </extensions>
```

## Environment

* WinSW version: v2.12.0
* WinSW package type:  WinSW-x64.exe
* Windows version: any
* Wrapped executable and version: java

**Comment by JuSenshi** [comment]
I have the same issue:

WinSW version I have used (always x64.exe):

- 2.12.0 (not working)
- 2.11.3 (not working)
- 2.10.0 (working)

I assume the changes in v2.11.0 have something to do with it. Is there any fix?

**Comment by robertschulze** [comment]
Apparently it depends not only on the version you are using but also the executable file. While, for me, WinSW-x64.exe is not working with the extension, WinSW.NET461.exe works well.

**Comment by cafhach** [comment]
Any news?

**Comment by DL444** [comment]
For `WinSW-x64.exe` of release 2.12.0, The `className` in config should be set to `WinSW.Plugins.SharedDirectoryMapper,WinSW.Plugins` or `WinSW.Plugins.RunawayProcessKillerExtension,WinSW.Plugins`. This should really be documented somewhere.

To derive the names yourself, use dotPeek or similar tools to show the assemblies in the executable. Find the plugin class name (e.g. `WinSW.Plugins.RunawayProcessKillerExtension`), and append the assembly name where the class is in (`WinSW.Plugins`), delimited by a comma.

![Screenshot 2024-04-25 035438](https://github.com/winsw/winsw/assets/10739819/1f30f0c5-6d60-476f-ae38-2bb6d3539eb1)

**Comment by harryssuperman** [comment]
Maybe could https://github.com/winsw/winsw/issues/662 also helping another people here.

@muskhd it seems to be related to the .NET Framework version. As i commented in 662, you could check wich version are you running. For me with a 4.8 or later Version the right class name was: `className="winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension"`
