### ISSUE TITLE
An error occurred during installation in Windows 7

### ISSUE THREAD

**Issue by WendelYu** [kohsuke/winsw#1073]
Unhandled exception. System.TypeInitializationException: The type initializer fo
r 'WinSW.Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'log4net.Core
.LoggerManager' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'log4net.Util
.SystemInfo' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.DateT
ime' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'handle')
   at System.ArgumentNullException.Throw(String)
   at System.ArgumentNullException.ThrowIfNull(IntPtr, String )
   at System.Runtime.InteropServices.NativeLibrary.GetExport(IntPtr, String)
   at System.DateTime.GetGetSystemTimeAsFileTimeFnPtr()
   at System.DateTime..cctor()
   --- End of inner exception stack trace ---
   at System.DateTime.get_UtcNow()
   at log4net.Util.SystemInfo..cctor()
   --- End of inner exception stack trace ---
   at log4net.Util.SystemInfo.AssemblyLocationInfo(Assembly myAssembly)
   at log4net.Core.LoggerManager.GetVersionInfo()
   at log4net.Core.LoggerManager..cctor()
   --- End of inner exception stack trace ---
   at log4net.Core.LoggerManager.GetLogger(Assembly repositoryAssembly, String n
ame)
   at log4net.LogManager.GetLogger(Assembly repositoryAssembly, String name)
   at log4net.LogManager.GetLogger(String name)
   at WinSW.Program..cctor()
   --- End of inner exception stack trace ---
   at WinSW.Program.Main(String[])

**Comment by lichangan18356288293** [comment]
mark,同样的问题,正在尝试解决

**Comment by little3201** [comment]
![Image](https://github.com/user-attachments/assets/3adf5bd4-6c80-4ac8-bfdd-0d69766960d5)

根据文档说明，需要.NET Framework 4.6.1 以上，但是 win 7 不自带，需要自行安装，
可查看：https://learn.microsoft.com/zh-cn/dotnet/framework/install/guide-for-developers

**Comment by bmarroquin** [comment]
Translation: Windows 7 is only supported when .Net Framework 4.6.1 or newer is installed.
