### ISSUE TITLE
RunawayProcessKillerExtension can lead to failed startup via Access denied

### ISSUE THREAD

**Issue by DrZ7** [kohsuke/winsw#1086]
If PID now belongs to a secured service, an exception is thrown, preventing a startup.

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at WinSW.Plugins.RunawayProcessKillerExtension.OnWrapperStarted()

## Environment

* WinSW version: 2.11.0

## Possible Solution

Catch exception without stopping?

**Comment by DrZ7** [comment]
related: https://github.com/winsw/winsw/pull/744
