### ISSUE TITLE
Service wrapper terminates at 00:00 and program's process is left orphaned

### ISSUE THREAD

**Issue by Helix751** [kohsuke/winsw#1088]
**Summary**. Describe the expected and actual behavior here.

I upgraded the wrapper from v2.8.0 to v2.12.0 and found that my console application (dev'd in golang), which has a cron to run some processes didn't run the routines at 00:00 and afterwards. The service (WinSW wrapper) quit without warning, nothing was written to the .out or .err log files, the files weren't "rolled" either. BUT the application process was left in a non-working zombie state and had to be terminated manually.

## Steps to reproduce
Upgrade the wrapper to 2.12.0 and for my app the behavior happens everyday at 00:00.
v2.8.0 works flawlessly.

Please clarify how to reproduce the issue.
Simply replacing the wrapper with v2.12.0 (haven't tried other versions in between)

If you need to attach your configuration, please do it pelow:

```xml
<service>
  <id>xyzApp</id>
  <name>xyzApp</name>
  <description>Data Transfer</description>
  <executable>xyz-app.exe</executable>

  <env name="CRONTAB" value="0 * * * *" />
  <env name="LOG_FILE_UPLOAD" value="true" />
  <env name="FORCE_SINGLE_EXECUTION" value="false" />
  <env name="IGNORE_UPLOAD_IF_FILE_ALREADY_EXISTS" value="false" />
  <env name="API_KEY" value="[APIkey deleted]" />
  <env name="MOCK_RESPONSES" value="false" />
  <env name="DESTINATION_SFTP_PRIVATE_KEY_PATH" value="[path deleted]" />
  <env name="DESTINATION_SFTP_MOCK_RESPONSES" value="false" />
  <env name="DESTINATION_SFTP_URL" value="[url deleted]" />
  <env name="DESTINATION_SFTP_USERNAME" value="[username deleted]" />
  <env name="DESTINATION_SFTP_PARENT_PATH" value="[path deleted]" />
  <env name="DESTINATION_SFTP_MOCK_RESPONSES" value="false" />

  <!--aca se especifica cuantos logs se quieren conservar, y
  con que criterio rotarlos-->
  <log mode="roll-by-size-time">
      <sizeThreshold>10240</sizeThreshold>
      <pattern>yyyyMMdd</pattern>
      <autoRollAtTime>00:00:00</autoRollAtTime>
      <keepFiles>30</keepFiles>
  </log>

  <!--si se agregan dependencias a otros servicios, este servicio
  no se iniciara hasta que esos otros servicios esten andando-->
  <!--<depend>SomeOtherService</depend>-->
</service>

```

## Environment

* WinSW version: 2.12.0
* WinSW package type: WinSW.NET4.exe (https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW.NET4.exe)
* Windows version: Windows Server 2019
* Wrapped executable and version: "internal project, compiled in golang" 

## Possible Solution
Reverting back to WinSW v2.8.0 solves the issue.

If you have suggestions on a fix for the bug, please describe it here.

**Comment by pitah81** [comment]
I'm having the same issue here, running a java application, except that the java application keeps working just that the winsw process dies giving me warnings as we have monitoring on both the windows services as well as the ports created by the java applications. If I check the Windows eventlog at the time of the crash I get two errors, one from .NET Runtime and one Application error. JSBService.exe is the winsw binary, just renamed by the software developers of the java application.

Could it have something to do with the log rotation? It says something about access to closed file as you can tell from the log.

`Application: JSBService.exe
CoreCLR Version: 6.0.1322.58009
.NET Version: 6.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Write(Byte[] , Int32 , Int32 )
   at WinSW.StreamCopyOperation.CopyLine()
   at WinSW.RollingSizeTimeLogAppender.CopyStreamWithRotation(StreamReader reader, String extension)
   at WinSW.RollingSizeTimeLogAppender.<>c__DisplayClass22_0.<LogOutput>b__0()
   at System.Threading.Thread.StartCallback()
`

`Faulting application name: JSBService.exe, version: 2.12.0.0, time stamp: 0x6387cc7a
Faulting module name: KERNELBASE.dll, version: 10.0.14393.6897, time stamp: 0x660f5eec
Exception code: 0xe0434352
Fault offset: 0x0000000000026ea8
Faulting process id: 0xdc8
Faulting application start time: 0x01dac23830b3180a
Faulting application path: D:\JSB14\TEST1.4\JSBService.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: bde8d3c6-a400-41c1-b08b-7b94ea6d654e
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by Helix751** [comment]
@pitah81 Did reverting to a former version solve the issue for you? As said, v2.8.0 solved it for me. I also believe log rotation may be the cause that exposes a bug in log/file renaming/rotation in the service handling processes, given the main program and its parameters didn't change between WinSW version change/downgrade.

**Comment by khaldi-yass** [comment]
@Helix751 Same issue encountered in version 2.12.0 when I upgraded from 2.3.0 (Java process is keeps running while the Windows service is stopped abruptly), I will downgrade to 2.8.0 to fix the issue as you confirmed it solves the issue, thank you.

Edit: V2.8.0 also has a bug in the rotate-by-size logs, the logs don't rotate after the threshold is reached, I guess rolling back to 2.3.0 is best now.

**Comment by maliksajidhussain** [comment]
I am facing the same issue with version 2.11.0. Do I need to downgrade to 2.3.0. wondering the roll-by-time-size issue was fixed in 2.3.0. Is there any workaround to rather downgrading to 2.3.0

**Comment by joao-costa-enghouse** [comment]
I think this problem was introduced by #770 .
To work around it, I tried to revert that commit on 2.12.0 and it seems to work.
