### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by cash1981** [kohsuke/winsw#222]
On my Windows Server 2012, I get Access Denied when trying to run my service.
I have started command prompt with administrator but still I get access denied.

I don't know why, and I don't know how I can get more debug info.

The log is like this

`
D:\PortableApps\Agent Forbrukslaan Windows service>agent-forbrukslaan.exe test
2017-05-29 10:25:39,968 INFO  - Starting ServiceWrapper in the CLI mode
2017-05-29 10:25:40,233 INFO  - Starting C:\Program Files\Java\jre1.8.0_131\bin  -Dspring.profiles.active=prod,jobb -jar agent-forbrukslaan.jar
2017-05-29 10:25:40,249 INFO  - Starting C:\Program Files\Java\jre1.8.0_131\bin  -Dspring.profiles.active=prod,jobb -jar agent-forbrukslaan.jar

2017-05-29 10:25:40,249 FATAL - Unhandled exception
System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at winsw.Util.ProcessHelper.StartProcessAndCallbackForExit(Process processToStart, String executable, String arguments, Dictionary`2 envVars, String workingDirectory, Nullable`1 priority, ProcessCompletionCallback callback)
   at winsw.WrapperService.StartProcess(Process processToStart, String arguments, String executable)
   at winsw.WrapperService.OnStart(String[] _)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at winsw.Util.ProcessHelper.StartProcessAndCallbackForExit(Process processToStart, String executable, String arguments, Dictionary`2 envVars, String workingDirectory, Nullable`1 priority, ProcessCompletionCallback callback)
   at winsw.WrapperService.StartProcess(Process processToStart, String arguments, String executable)
   at winsw.WrapperService.OnStart(String[] _)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
`

If I start the program from the same command prompt:
"C:\Program Files\Java\jre1.8.0_131\bin\java"  -Dspring.profiles.active=prod,jobb -jar agent-forbrukslaan.jar

Then it runs fine. So to me it seems like the service doesn't get the correct access for some strange reason.

**Comment by oleg-nenashev** [comment]
It may happen if WinSW service account has not permission to launch the executable file.

**Comment by cash1981** [comment]
How can I check that?

**Comment by oleg-nenashev** [comment]
@cash1981 depends on your OS version and available tools. The best way is to logic as the service account and to check manually (though it is not ideal). Just contact your sys admin

**Comment by cash1981** [comment]
@oleg-nenashev Its windows server 2012. I have admin rights on the username. Any suggestions on tools I can install and check?

**Comment by pnikonowicz** [comment]
See if you can start and install services manually using the same account that you plan on installing and running your service.

**Comment by fontecha** [comment]
@cash1981  We have the same issue with similar configuration  (Windows Server 2012 R2 Standard de 64bits and JRE1.8 64bits)
did you resolve it?

thanking you in advance

**Comment by cash1981** [comment]
I think I had the wrong exe file. I downloaded it again and it world for some unknown reason
