### ISSUE TITLE
can't install service with winsw

### ISSUE THREAD

**Issue by cqzongjian** [kohsuke/winsw#255]
I can't install the service with winsw. How is it? There is the log: 
2017-11-16 08:19:20,802 INFO  - Installing the service with id 'web2'
2017-11-16 08:19:20,848 FATAL - WMI Operation failure: UnknownFailure
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

**Comment by Cylindric** [comment]
I'm having a similar problem. I assume you resolved it, as you closed it immediately?
