### ISSUE TITLE
No timestamps in .err.log file

### ISSUE THREAD

**Issue by kukraPOC** [kohsuke/winsw#274]
Is it possible to add a timestamp to the err.log ? 
Or is it only meant to be used as a debug file ?

`path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.normalize (path.js:345:5)
    at fileAppender 
    .....
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');`

**Comment by oleg-nenashev** [comment]
It should be actually resolved by streaming logs through log4net. But yes, the default configuration does not do it, it relies on the application to produce logs with timestamps. It is enough IMHO, but a new option could be introduced to enable timestamps in WinSW
