### ISSUE TITLE
Application will break when log try to roll over on the same day with file threshold

### ISSUE THREAD

**Issue by zhengye1** [kohsuke/winsw#310]
Here is the config I have for the xml file 
```
<configuration>
   <!-- 
SECTION: Mandatory options
All options in other sections are optional 
-->
   <!-- ID of the service. It should be unique accross the Windows system-->
   <id>FDSpringBoot</id>
   <!-- Display name of the service -->
   <name>First Data Spring Boot Windows Service</name>
   <!-- Service description -->
   <description>First Data Spring boot application</description>
   <!-- we need to execute java -jar ./win-service.jar -->
   <executable>java</executable>
   <!--<arguments>-Dspring.profiles.active=prod -jar %BASE%\fdr-0.0.1-SNAPSHOT.jar</arguments> -->
   <arguments>-Dspring.profiles.active=prod -jar %BASE%\fdr-1.0.0.jar</arguments>
   <logpath>%BASE%\logs</logpath>
   <log mode="roll-by-size-time">
      <sizeThreshold>10240</sizeThreshold>
      <pattern>yyyyMMdd</pattern>
      <autoRollAtTime>00:00:00</autoRollAtTime>
      <zipOlderThanNumDays>7</zipOlderThanNumDays>
      <zipDateFormat>yyyyMMdd</zipDateFormat>
   </log>
</configuration>
```

For example, on April 10, when the log file get 10240 KB, and old file with (hashtag)0001.out.log is created, and somehow it breaks. During the event log I saw 

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Flush(Boolean)
   at winsw.RollingSizeTimeLogAppender.CopyStreamWithRotation(System.IO.Stream, System.String)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

What is the issue for this? Because it seems like the process was not kill properly once this exception exists, and I need to manually kill that service and restart again

UPDATE:
It seems like if I manually change the thing, the day roll over also have issue and break.

**Comment by zhengye1** [comment]
Same issue as #314 , I closed this one
