### ISSUE TITLE
Periodic Logrotation throws unhandled System.ArgumentException

### ISSUE THREAD

**Issue by BernhardBerbuir** [kohsuke/winsw#40]
The periodic log rotation throws an System.ArgumentException:

    at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
    at winsw.TimeBasedRollingLogAppender.CopyStreamWithDateRotation(Stream data, String ext)
    at winsw.TimeBasedRollingLogAppender.<>c__DisplayClass2.<log>b__1()
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Threading.ThreadHelper.ThreadStart()

This occurs when two lines have to be logged during log rotation. The command

    w.Write(buf, offset, i + 1);

uses an invalid length for the second time it is invoked.

**Comment by oleg-nenashev** [comment]
Marking as fixed
