### ISSUE TITLE
start service if service running 

### ISSUE THREAD

**Issue by VashchenkoVitaliy** [kohsuke/winsw#402]
Hi!
When you restart the service already running, it displays the following message:
2020-02-07 09:24:35,150 INFO  - Starting the service with id 'service-0.0.2'
2020-02-07 09:24:35,212 FATAL - WMI Operation failure: ServiceAlreadyRunning
WMI.WmiException: ServiceAlreadyRunning
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: ServiceAlreadyRunning
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

You can replace it with a more pleasant one for users, for example: "Service is running"
Thanks!

**Comment by NextTurn** [comment]
#385

**Comment by oleg-nenashev** [comment]
I agree that a log entry still makes sense in this case. My plan to cut a release on the weekend so that I am available if something goes wrong. We can get this improvement into it

**Comment by VashchenkoVitaliy** [comment]
thanks, ready to be a tester :)
