### ISSUE TITLE
UnknownFailure exception when service already exists

### ISSUE THREAD

**Issue by christ66** [kohsuke/winsw#55]
When winsw executes an install, and the service already exists an UnknownFailure is thrown:

```
WMI.WmiException: UnknownFailure
  at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
  at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] result)
  at WMI.Win32ServicesProxy.Create(String, String, String, ServiceType, ErrorControl, StartMode, Boolean, String[])
  at winsw.WrapperService.Run(String[] _args)
  at winsw.WrapperService.Main(String[] args)
```

Steps to reproduce:
1. Install winsw service (`jenkins-slave.exe install`).
2. Stop the service (`sc stop jenkins`)
3. Reinstall the service (`jenkins-slave.exe install`).

I tried to rename the service, and it still throws this exception. This is most likely due to the modifying the display name instead of the service name which was a bit confusing.

Only workaround is to delete the service (`sc delete jenkins`) and then the service could be installed again.

**Comment by oleg-nenashev** [comment]
Probably causes #34
