### ISSUE TITLE
[JENKINS-22692] - Shutdown exception. Cannot get Child Pids

### ISSUE THREAD

**Issue by danielsantiago** [kohsuke/winsw#59]
Hi,

I'm getting this shutdown exception when I try to restart the server. I'm using the master branch code.
It appears like is having problem getting the process pids with GetChildPids.

OS: Windows 7

```
2014-12-01 20:56:12 - ProcessKill 10804
2014-12-01 20:56:14 - Shutdown exception
Message:A system shutdown is in progress. (Exception from HRESULT: 0x8007045B)
Stacktrace:   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at winsw.WrapperService.GetChildPids(Int32 pid)
   at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
   at winsw.WrapperService.StopIt()
   at winsw.WrapperService.OnShutdown()
```

**Comment by oleg-nenashev** [comment]
Also causes https://issues.jenkins-ci.org/browse/JENKINS-22692

**Comment by oleg-nenashev** [comment]
A major rework is required (if we don't want just to suppress exceptions). Seems the bug in winsw-2.0 scope

**Comment by oleg-nenashev** [comment]
I have added suppression of this exception. Even if WinSW fails to retrieve child PIDs, it will try to kill the spawned process
