### ISSUE TITLE
Access is denied error for the NT Authority\Network Service security principal

### ISSUE THREAD

**Issue by igolotin** [kohsuke/winsw#872]
**Summary**.

I have trouble running WinSW under restricted account. NT Authority\Network Service does not have full access right to the local computer.

**Expected:**

Service starts despite not having rights to modify the service

**Actual:**

Service failed to start at early stages

## Steps to reproduce

1. Specify NT Authority\Network Service as the username in the *myapp.xml*
```
        <serviceaccount>
		<username>NT AUTHORITY\NetworkService</username>
	</serviceaccount>
```
2. Register the service (run the cmd as administrator)
`myapp.exe install`
3. Check the service is actually configured to start as Network Service using the Service Manager GUI
4. Write debug output to the executable bat file (for testing purposes)
5. Try to run the service
5. Got error both in the interface and in the *myapp.wrapper.log*
6. See that .bat file had not performed expected debug output

## myapp.wrapper.log

```
2021-10-13T14:13:27.496 DEBUG console - Starting WinSW in service mode.
2021-10-13T14:13:27.618 FATAL console - Failed to open the service. Access is denied.
```

## Environment

* WinSW version: 3.0.0+71f08e5e73585cf06e75f2ad1b90dff972d04b7d (alpha 10)
* WinSW package type: WinSW-x64.exe
* Windows version: Microsoft Windows Server 2012 R2 Standard 6.3.9600 N/A Build 9600
* Wrapped executable and version: bat file to run a chromium instance

## Possible Solution

Apparently the error is produced from the WinSW.Native.ServiceManager.OpenService call to the WinSW.Native.ServiceApis.OpenService
The method has ServiceAccess access = ServiceAccess.All default parameter which should be changed to something less demanding. Since full access require administrator privileges to run and Network Service does not have them

**Comment by viceice** [comment]
Seeing same issue:

```
2022-11-03 15:42:50,709 DEBUG - Starting WinSW in console mode
2022-11-03 15:42:53,396 DEBUG - Starting WinSW in console mode
2022-11-03 15:58:11,630 ERROR - Thread failed unexpectedly
WinSW.CommandException: Failed to open the service control manager database. Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at WinSW.Native.Throw.Command.Win32Exception(String message)
   at WinSW.Native.ServiceManager.Open(ServiceManagerAccess access)
   at WinSW.WrapperService.SignalStopped()
   at WinSW.WrapperService.<>c__DisplayClass31_0.<StartProcess>g__OnProcessCompleted|0(Process proc)
   at WinSW.Util.ProcessHelper.<>c__DisplayClass6_0.<StartThread>b__0()
2022-11-04 08:35:18,485 DEBUG - Starting WinSW in console mode
2022-11-04 08:35:18,499 FATAL - Unhandled exception
```

- #980

**Comment by viceice** [comment]
> autorefresh

That doesn't exist on v2.11.0 😕

**Comment by viceice** [comment]
Downgrade is also not an option because of 
- #814

**Comment by viceice** [comment]
~my (hopefully working) workaround is to make jenkins user local admin again~ Doesn't work 😕

**Comment by viceice** [comment]
@nxtn Any chance to catch this and exit winsw? Otherwise the service is still running in broken state.
